development:
  adapter: postgresql
  encoding: unicode
  database: example_development
  pool: 5
  username:
  password:

production:
  database: example_production
  adapter: postgresql
  host: localhost
  password:
